### ISSUE TITLE
How Can i remove the warn ?

### ISSUE THREAD

**Issue by SilentzZ** [FOCI-DEV/Get-Discord-Token#1]
Hi!
Its works for me perfectly but i would love to remove the warn. I tryed it a little on myself but with no good result. Is it possible to remove it, or does i need to be there ?

**Comment by FOCI-DEV** [comment]
> Hi!
> Its works for me perfectly but i would love to remove the warn. I tryed it a little on myself but with no good result. Is it possible to remove it, or does i need to be there ?

try this https://github.com/FOCI-DEV/Get-Discord-Token/blob/no-warn/get-discord-token.js
